---
namespace: splunk
name: itsi
authors:
  - Ansible Ecosystem Engineering team
  - Shahar Golshani <sgolshan@redhat.com>
  - Ron Gershburg <rgershbu@redhat.com>
description: Ansible Collection for Splunk IT Service Intelligence
license_file: LICENSE
tags: ["monitoring", "splunk"]
repository: https://github.com/ansible-collections/splunk.itsi
documentation: https://github.com/ansible-collections/splunk.itsi
homepage: https://github.com/ansible-collections/splunk.itsi
issues: https://github.com/ansible-collections/splunk.itsi/issues
readme: README.md
version: "1.0.0"
dependencies:
  ansible.netcommon: ">=6.0.0"
