---
namespace: splunk
name: itsi
authors:
  - Ansible Ecosystem Engineering team
  - Shahar Golshani <sgolshan@redhat.com>
  - Ron Gershburg <rgershbu@redhat.com>
description: Ansible Collection for Splunk IT Service Intelligence
license_file: LICENSE
tags: ["monitoring", "splunk"]
repository: https://github.com/ansible-collections/splunk.itsi
documentation: https://github.com/ansible-collections/splunk.itsi
homepage: https://github.com/ansible-collections/splunk.itsi
issues: https://github.com/ansible-collections/splunk.itsi/issues
readme: README.md
version: "1.0.0"
dependencies:
  ansible.netcommon: ">=6.0.0"
build_ignore:
  # https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - codecov.yml
  - sonar-project.properties
  - .ansible-lint
  - .azure-pipelines
  - .cursor
  - .darglint
  - .flake8
  - .github
  - .gitignore
  - .pre-commit-config.yaml
  - .prettierignore
  - .pytest_cache
  - .vscode
  - .yamllint
